### ISSUE TITLE
Ломает плюрализацию russian

### ISSUE THREAD

**Issue by yura** [kslazarev/numbers_and_words#22]
config/locales/ru.yml

``` yml
ru:
  items:
    one: '%{count} товар'
    few: '%{count} товара'
    many: '%{count} товаров'    
```

rails c:

```
> I18n.t :items, :count => 101
 => "101 товаров"
```

Должно быть:

```
> I18n.t :items, :count => 101
 => "101 товар"
```
